apiVersion: v1
data:
 clusternetworkprofile_overrides: |
  config_overrides:
    aci_cni_config:
      aci_config:
        aep: bm-srvrs-calico-aep
    registry:
      image_prefix: quay.io/cko
      network_operator_version: 0.9.0.d04f56f
    aci_config:
      cluster_l3out:
        aep: bm-srvrs-calico-aep
        svi:
          type: floating
          floating_ip: 2.100.101.100/24
          secondary_ip: 2.100.101.254/24
          vlan_id: 13
          mtu: 9000
        bgp:
          peering:
            remote_as_number: 64512
            aci_as_number: 2
      l3out:
        name: l3out-3
        external_networks:
        - l3out-3_epg
      vrf:
        name: l3out-3_vrf
        tenant: common
    net_config:
      node_subnet: 2.100.101.1/24
      pod_subnet: 20.2.0.1/16
      extern_dynamic: 20.3.0.1/16
      cluster_svc_subnet: 10.96.0.0/12
    cko_proxy_config:
      http_proxy: http://proxy.myorg.com:80
      https_proxy: http://proxy.myorg.com:80
      no_proxy: 10.96.0.1
    topology:
      rack:
      - id: 1
        aci_pod_id: 1
        leaf:
        - id: 101
        - id: 102
        node:
        - name: k8s-node1
        - name: k8s-node2
    fabricinfra:
      name: k8s-bm-2
    cni: calico
kind: ConfigMap
metadata:
  name: calicoacicluster
  namespace: netop-manager
  labels:
   distro: kubernetes
   location: on-prem
   pod-network: calico