apiVersion: v1
data:
 clusternetworkprofile_overrides: |
  config_overrides:
    aci_cni_config:
      aci_config:
        aep: bm-srvrs-aep
        vmm_domain:
          encap_type: vxlan
          mcast_range:
              start: 225.114.1.1
              end: 225.114.255.255
      kube_config:
        opflex_agent_prometheus: false
        ovs_memory_limit: 0.75Gi
        image_pull_policy: Always
      logging:
        controller_log_level: debug
        hostagent_log_level: debug
        opflexagent_log_level: debug
      net_config:
        extern_static: 10.4.0.1/16
        service_vlan: 102
        node_svc_subnet: 10.5.0.1/16
      registry:
        aci_containers_controller_version: kmr2-test
        acc_provision_operator_version: kmr2-test
        aci_containers_host_version: kmr2-test
        aci_containers_operator_version: kmr2-test
        cnideploy_version: kmr2-test
        opflex_agent_version: kmr2-test
        openvswitch_version: kmr2-test
    aci_config:
      l3out:
        name: sauto_l3out-1
        external_networks:
        - sauto_l3out-1_epg
      vrf:
        name: sauto_l3out-1_vrf
        tenant: common
    registry:
      image_prefix: quay.io/cko
      network_operator_version: 0.9.1.d04f56f
    net_config:
      node_subnet: 1.100.101.1/24
      pod_subnet: 10.6.0.1/16
      extern_dynamic: 10.3.0.1/16
      kubeapi_vlan: 101
      cluster_svc_subnet: 10.96.0.0/12
    cko_proxy_config:
      http_proxy: http://proxy.myorg.com:80
      https_proxy: http://proxy.myorg.com:80
      no_proxy: 10.96.0.1
    fabricinfra:
      name: k8s-bm-2
    cni: aci
    distro:
      type: kubernetes
      release: "1.24"
kind: ConfigMap
metadata:
  name: bm2acicni
  namespace: netop-manager
  labels:
   distro: kubernetes
   location: on-prem
   pod-network: aci