apiVersion: netop.mgr/v1alpha1
kind: ClusterNetworkProfile
metadata:
  name: k8s-dev-001                                     # because config map for NetworkProfile is defined per k8s/ocp cluster it can have the same name as clusterProfile.
  namespace: netop-manager
  labels:                                               # labels definition to be matched by clusterProfile
    cni: calico                                         # unique labels to distiguish config-map for clusterNetworkProfile among the others.
    distro: kubernetes                                  # other labels can be optionally added for description
    environment: dev                                    
    netProfile: k8s-dev-001
    platform: baremetal    
spec:
  config_overrides:                                      # this section supports all overrides that are possible to do in the clusterProfile or clusterGroupProfile
    registry:                    
      image_prefix: quay.io/cko
      network_operator_version: 0.9.1.d04f56f
    aci_config:                                          # aci_config section consists of ACI related configuration - Tenant, VRF, L3out, BGP, AEP.
      cluster_l3out:
        aep: bm-srvrs-aep
        svi:
          floating_ip: 10.255.1.100/24
          secondary_ip: 10.255.1.254/24
          vlan_id: 13
          mtu: 9000
        bgp:
          peering:
            remote_as_number: 64514
            aci_as_number: 65001
      l3out:                                            # L3out for external connectivity - it must exists before applying clusterProfile.
        name: l3out-3
        external_networks:
        - l3out-3_epg
      vrf:
        name: l3out-3_vrf
        tenant: common
    net_config:                                         # this section specifies K8s cluster networks assignments
      node_subnet: 10.255.1.1/24                        # node network
      pod_subnet: 10.2.0.1/16                           # pod network
      extern_dynamic: 10.11.1.1/24                      # network from which the external IP addresses will be assigned when exposing service using externalTrafficPolicy
      cluster_svc_subnet: 10.96.0.0/12                  # internal service network. By default it will not be advertised to ACI.
    cko_proxy_config:
      http_proxy: http://proxy.myorg.com:80
      https_proxy: http://proxy.myorg.com:80
      no_proxy: 10.96.0.1
    topology:                                           # custom topology used to annotate K8s node running Calico routers to peer with the correct ACI Leafs
      rack:
      - id: 1
        aci_pod_id: 1
        leaf:
        - id: 101
          local_ip: 10.255.1.252/24
        - id: 102
          local_ip: 10.255.1.253/24
        node:
        - name: k8s-node1
        - name: k8s-node2
        - name: k8s-node3
    fabricinfra:                                        # match name of the fabricInfra resource.
      name: aci-fab-01
    cni: calico                                         # Mandatory field to specify cni type.
    connectivity_checker:
      error_pods_reporting_enable: true
      reachability_test_enable:
        periodic_sync:
          enable_updates: true
          interval: 120
        external_url:
          url: 'google.com'
      reachability_tests:
        - pod_to_pod
        - pod_to_node
        - pod_to_clusterIP
        - pod_to_service
        - pod_to_LB_VIP
        - pod_to_NodePort
        - pod_to_External
        - node_to_node
        - node_to_pod
        - node_to_clusterIP
        - node_to_LB_VIP