apiVersion: netop.mgr/v1alpha1
kind: ClusterProfile
metadata:
  name: k8s-dev-002
  namespace: netop-manager
spec:
  cluster_name: k8s-dev-002
  cluster_network_profile_selector:
    matchLabels:
      cni: aci
      distro: kubernetes
      environment: dev
      netProfile: ocp-dev-002
      platform: esx