apiVersion: netop.mgr/v1alpha1
kind: ClusterProfile
metadata:
  annotations:
    notification-controller.netop.mgr/created: "true"
  creationTimestamp: "2022-11-02T03:52:14Z"
  finalizers:
  - clusterprofile.netop.mgr/finalizer
  generation: 2
  labels:
    autodetect-cluster.notification-controller.netop.mgr: bm2acicni
  name: auto-bm2acicni
  namespace: netop-manager
  resourceVersion: "72773"
  uid: 490b6119-56e5-4899-8f0f-ccd6e9eee283
spec:
  cluster_name: bm2acicni
  cluster_network_profile_selector:
    matchLabels:
      autodetect-cluster.notification-controller.netop.mgr: bm2acicni
  cni: aci
  config_overrides:
    aci_cni_config:
      aci_config:
        vmm_domain:
          mcast_range: {}
          nested_inside: {}
      kube_config:
        drop_log_config: {}
        istio_config: {}
        multus: {}
        nodepodif_config: {}
        operator_managed_config: {}
        sriov_config: {}
      logging: {}
      net_config: {}
      registry: {}
    aci_config:
      cluster_l3out:
        bgp:
          peering: {}
        svi: {}
      l3out: {}
      physical_domain: {}
      vrf: {}
    calico_cni_config: {}
    cko_git_config: {}
    cko_proxy_config: {}
    connectivity_checker:
      reachability_test_enable:
        external_url: {}
        periodic_sync: {}
    lb_config: {}
    monitoring_config: {}
    net_config: {}
    registry: {}
    service_mesh_config: {}
  distro:
    flavor: kubernetes-1.20
  fabricinfra: {}
  operator_config:
    mode: unmanaged
status:
  cluster_network_profile_name: auto-bm2acicni
  context:
    aep: bm-srvrs-calico-aep
    l3out:
      external_networks:
      - l3out-3_epg
      name: l3out-3
    vrf:
      name: l3out-3_vrf
      tenant: common
  deployment_scripts:
  - 'Argo App: https://raw.githubusercontent.com/networkoperator/demo-cluster-manifests/notif_test/workload/argo/bm2acicni/argo_app.yaml'
  - 'Netop Manager Deployment: https://raw.githubusercontent.com/networkoperator/demo-cluster-manifests/notif_test/workload/config/bm2acicni/netop-manager-deployment.yaml'
  - 'Netop Platform Networking: https://raw.githubusercontent.com/networkoperator/demo-cluster-manifests/notif_test/workload/config/bm2acicni/installer-platform.yaml'
  - 'Netop Installer Networking: https://raw.githubusercontent.com/networkoperator/demo-cluster-manifests/notif_test/workload/config/bm2acicni/installer-networking.yaml'
  external_subnets:
  - 10.3.0.1/16
  - 10.4.0.1/16
  fabricinfra:
    context: context-2
    name: k8s-bm-2
  internal_subnets:
  - 1.100.101.1/16
  - 2.100.101.1/16
  - 10.5.0.1/16
  mcast_subnets:
  - 225.114.0.0/16
  node_subnet: 1.100.101.1/16
  node_vlan: 101
  operator_config:
    mode: unmanaged
    version: 0.9.1
  pod_subnet: 2.100.101.1/16
  ready: true
  vlans:
  - 101
  - 102