apiVersion: netop.mgr/v1alpha1
kind: ClusterProfile
metadata:
  name: k8s-prod-001                   # name of the workload cluster that will be uniquely identified in CKO control cluster.
  namespace: netop-manager
spec:
  cluster_group_profile_selector:
    matchLabels:                       # match labels to select clusterGroupProfile
      distro: kubernetes
      location: az01                  
      cni: calico
      platform: baremetal
      environment: prod
  cluster_name: k8s-prod-001           # unique name that will be used as system_id (for aci-cni this will be a tenant name)