apiVersion: netop.mgr/v1alpha1
kind: ClusterGroupProfile
metadata:
  name: k8s-prod-acicni-az02
  namespace: netop-manager
  labels:                                     # unique labels to distiguish ClusterGroupProfiles among the others.
    cni: aci
    distro: kubernetes
    environment: prod
    location: az02
    platform: esx
spec:
  selector:
    matchLabels:
      fabric: aci-fab-02
      site: az02
  config_overrides:    
    cni: aci
    distro:                                   # indicate which flavor of openshift will be applied. It follows strict naming:
      type: kubernetes                        # kubernetes or openshift
      release: "1.24"                         # supported releases OCP: 4.6, 4.7, 4.8, 4.9, 4.10, 4.11; K8s: 1.20, 1.21, 1.22, 1.23, 1.24, 1.25
      platform: esx                           # supported platforms: esx, baremetal, openstack
    operator_config:
      target_version: 0.9.1
    connectivity_checker:                       # (optional) connectivity check tool to test and report connectivity status.
      error_pods_reporting_enable: true
      reachability_test_enable:
        periodic_sync:
          enable_updates: true
          interval: 120
        external_url:
          url: 'google.com'
      reachability_tests:
        - pod_to_pod
        - pod_to_node
        - pod_to_clusterIP
        - pod_to_service
        - pod_to_LB_VIP
        - pod_to_NodePort
        - pod_to_External
        - node_to_node
        - node_to_pod
        - node_to_clusterIP
        - node_to_LB_VIP