apiVersion: netop.mgr/v1alpha1
kind: ClusterProfile
metadata:
  name: k8s-prod-002                        # name of the workload cluster that will be uniquely identified in CKO control cluster.
  namespace: netop-manager
spec:
  cluster_group_profile_selector:
    matchLabels:                            # match labels to select clusterGroupProfile
      cni: aci
      distro: kubernetes
      environment: prod
      location: az02
      platform: esx
  cluster_name: k8s-prod-002                # unique name that will be used as system_id (for aci-cni this will be a tenant name)